version: '3.8'

volumes:
  # 覆盖顶层的 storage 配置
  # 在 Mac 上，直接使用简易驱动，不使用带 device 路径的 bind 模式
  storage:
    driver: local

services:
  backend:
    volumes:
      # 这种简写语法在 Mac 上会自动把相对路径 ./data 转换为绝对路径并正确挂载
      - ./data:/var/lib/sqlite
      - ./backend:/app
      - "/app/node_modules"

  database:
    volumes:
      # 同样，在这里直接指定挂载到 ./data
      - ./data:/var/lib/sqlite