filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log
  parsers:
    - ndjson:
        target: ""
        overwrite_keys: true
        add_error_key: true


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true


processors:
- add_docker_metadata: ~


setup.kibana:
  host: https://ft-kibana:5601
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities:
      - /usr/share/filebeat/certs/ca/ca.crt

# output.elasticsearch:
#   hosts: ${ELASTIC_HOSTS}
#   username: ${ELASTIC_USER}
#   password: ${ELASTIC_PASSWORD}
#   ssl.enabled: true
#   ssl.certificate_authorities: "certs/ca/ca.crt"

output.elasticsearch:
  hosts: ["https://ft-elasticsearch:9200"]
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl:
    certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
    certificate: "/usr/share/filebeat/certs/ft-filebeat/ft-filebeat.crt"
    key: "/usr/share/filebeat/certs/ft-filebeat/ft-filebeat.key"

