# =======================================================
# srver-section 1: HTTP (8080) -> HTTPS (8443) redirct
# =======================================================
server {
    listen 8080;
    listen [::]:8080;
    server_name transcendence.42.fr;
    return 301 https://$host$request_uri;
}

# =======================================================
# srver-section 2: HTTPS (8443) - SPA dist & API proxy
# =======================================================
server {
    listen 8443 ssl;
    listen [::]:8443 ssl;
    server_name transcendence.42.fr;

    ssl_certificate /run/secrets/nginx_certificate;
    ssl_certificate_key /run/secrets/nginx_private_key;

    location /api/ {
        proxy_pass http://ft-backend:8080;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }
}
