# =======================================================
# server-section 1: HTTP (8080) -> HTTPS (8443) redirect
# =======================================================
server {
    listen 8080;
    listen [::]:8080;
    server_name transcendence.42.fr _;
    return 301 https://$host$request_uri;
}

# =======================================================
# server-section 2: HTTPS (8443) - SPA dist & API proxy
# =======================================================
server {
    listen 8443 ssl;
    listen [::]:8443 ssl;
    server_name transcendence.42.fr _;

    ssl_certificate /run/secrets/nginx_certificate;
    ssl_certificate_key /run/secrets/nginx_private_key;

    location /api/ {
        modsecurity_rules 'SecRuleRemoveById 911100'; # ALLOW DELETE METHOD
        modsecurity_rules 'SecRequestBodyAccess Off'; # ALLOW BINARY FILE
        proxy_pass http://ft-backend:8080/api/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Connection "";
    }

    location /ws/ {
        proxy_pass http://ft-backend:8080/ws/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }
}

# =======================================================
# server-section 3: metrics only
# =======================================================
server {
    listen 8081;
    server_name localhost;

    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow 172.19.0.0/16;
        deny all;
    }
}
